module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  WALLET_NOT_ACTIVATED: "WALLET_NOT_ACTIVATED",
  XRP_ACCOUNT_NOT_ACTIVATED: "XRP_ACCOUNT_NOT_ACTIVATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};
