const RECEIVED_NOTIFICATION_MAX_EVENT_AGE_MS = 24 * 60 * 60 * 1000;

const RECEIVED_NOTIFICATION_MINIMUM_AMOUNT_BY_ASSET = Object.freeze({
  XRP: "0.0001",
  SOL: "0.000001",
  BNB: "0.000001",
});

const DEFAULT_RECEIVED_NOTIFICATION_MINIMUM_AMOUNT = "0";

module.exports = {
  RECEIVED_NOTIFICATION_MAX_EVENT_AGE_MS,
  RECEIVED_NOTIFICATION_MINIMUM_AMOUNT_BY_ASSET,
  DEFAULT_RECEIVED_NOTIFICATION_MINIMUM_AMOUNT,
};
